# Generated by Django 5.2.16 on 2026-07-17 17:04

import accounts.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=24, unique=True, verbose_name='學號 / Student ID')),
                ('name_zh', models.CharField(max_length=100, verbose_name='中文姓名 / Chinese name')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='英文姓名 / English name')),
                ('role', models.CharField(choices=[('ADMIN', '管理員 / Admin'), ('TUTOR', '輔導者 / Tutor'), ('TUTEE', '受輔導者 / Tutee')], max_length=10, verbose_name='身分 / Role')),
                ('education_level', models.CharField(choices=[('BACHELOR', "大學 / Bachelor's"), ('MASTER', "碩士 / Master's"), ('DOCTORAL', '博士 / Doctoral'), ('NA', '不適用 / Not applicable')], default='NA', max_length=12, verbose_name='學制 / Degree level')),
                ('identity_category', models.CharField(choices=[('LOCAL', '本地生 / Local student'), ('OVERSEAS', '僑生 / Overseas Chinese student'), ('INTERNATIONAL', '外籍生 / International student')], max_length=16, verbose_name='學生類別 / Student category')),
                ('program_source', models.CharField(choices=[('NTNU', '師大外籍生 / NTNU international student'), ('MARYLAND', '馬里蘭大學 / University of Maryland'), ('OTHER', '其他合作計畫 / Other partner program'), ('NA', '不適用 / Not applicable')], default='NA', max_length=16, verbose_name='所屬計畫 / Program')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='可註冊 / Registration enabled')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='註冊時間 / Claimed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '學生名冊 / Roster entry',
                'verbose_name_plural': '學生名冊 / Roster entries',
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', '管理員 / Admin'), ('TUTOR', '輔導者 / Tutor'), ('TUTEE', '受輔導者 / Tutee')], default='TUTOR', max_length=10, verbose_name='角色 / Role')),
                ('account_status', models.CharField(choices=[('ACTIVE', '啟用 / Active'), ('SUSPENDED', '停用 / Suspended')], default='ACTIVE', max_length=12, verbose_name='帳號狀態 / Account status')),
                ('name_zh', models.CharField(blank=True, max_length=100, verbose_name='中文姓名 / Chinese name')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='英文姓名 / English name')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='電話 / Phone')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('roster_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='accounts.rosterentry', verbose_name='名冊資料 / Roster entry')),
            ],
            options={
                'verbose_name': '使用者 / User',
                'verbose_name_plural': '使用者 / Users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', accounts.models.CSLUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80, verbose_name='事件類型 / Event type')),
                ('description', models.CharField(max_length=255, verbose_name='說明 / Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '稽核紀錄 / Audit log',
                'verbose_name_plural': '稽核紀錄 / Audit logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(choices=[('Q1', '我第一所就讀的小學名稱？ / What was the name of my first elementary school?'), ('Q2', '我童年最喜歡的食物？ / What was my favorite childhood food?'), ('Q3', '我最喜歡的一本書？ / What is my favorite book?'), ('Q4', "我第一位導師的姓氏？ / What was my first homeroom teacher's surname?"), ('Q5', '我最想造訪的城市？ / Which city would I most like to visit?'), ('Q6', '我自訂的一句秘密短語？ / What is my personal secret phrase?')], max_length=2)),
                ('answer_1_hash', models.CharField(max_length=256)),
                ('question_2', models.CharField(choices=[('Q1', '我第一所就讀的小學名稱？ / What was the name of my first elementary school?'), ('Q2', '我童年最喜歡的食物？ / What was my favorite childhood food?'), ('Q3', '我最喜歡的一本書？ / What is my favorite book?'), ('Q4', "我第一位導師的姓氏？ / What was my first homeroom teacher's surname?"), ('Q5', '我最想造訪的城市？ / Which city would I most like to visit?'), ('Q6', '我自訂的一句秘密短語？ / What is my personal secret phrase?')], max_length=2)),
                ('answer_2_hash', models.CharField(max_length=256)),
                ('question_3', models.CharField(choices=[('Q1', '我第一所就讀的小學名稱？ / What was the name of my first elementary school?'), ('Q2', '我童年最喜歡的食物？ / What was my favorite childhood food?'), ('Q3', '我最喜歡的一本書？ / What is my favorite book?'), ('Q4', "我第一位導師的姓氏？ / What was my first homeroom teacher's surname?"), ('Q5', '我最想造訪的城市？ / Which city would I most like to visit?'), ('Q6', '我自訂的一句秘密短語？ / What is my personal secret phrase?')], max_length=2)),
                ('answer_3_hash', models.CharField(max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '安全問題 / Security questions',
                'verbose_name_plural': '安全問題 / Security questions',
            },
        ),
    ]
