# Generated by Django 5.2.16 on 2026-07-17 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=256, verbose_name='密碼雜湊 / Password hash')),
                ('expires_at', models.DateTimeField(verbose_name='到期時間 / Expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roster_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_draft', to='accounts.rosterentry', verbose_name='名冊資料 / Roster entry')),
            ],
            options={
                'verbose_name': '註冊草稿 / Registration draft',
                'verbose_name_plural': '註冊草稿 / Registration drafts',
            },
        ),
    ]
