# Generated by Django 5.2.16 on 2026-07-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_securityquestionanswer_question_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterentry',
            name='role',
            field=models.CharField(choices=[('ADMIN', '管理員 / Admin'), ('TUTOR', '老師 / Teacher'), ('TUTEE', '學生 / Student')], max_length=10, verbose_name='身分 / Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', '管理員 / Admin'), ('TUTOR', '老師 / Teacher'), ('TUTEE', '學生 / Student')], default='TUTOR', max_length=10, verbose_name='角色 / Role'),
        ),
    ]
