# Generated by Django 5.2.16 on 2026-07-22 17:59

import django.db.models.deletion
from django.db import migrations, models


PROGRAM_SEED = [
    {
        "code": "NTNU",
        "name_zh": "師大外籍生",
        "name_en": "NTNU international student",
        "is_active": True,
        "allow_tutee_initiate_invitation": False,
        "tutee_can_download_hours": True,
        "tutee_certificate_filename": "ntnu_tutee_hours_certificate.pdf",
        "tutee_certificate_plan_name": "外籍生華語輔導計畫",
        "tutee_certificate_activity_text": "接受華語輔導",
        "tutor_certificate_filename": "ntnu_csl_hours_certificate.pdf",
        "tutor_certificate_plan_name": "外籍生華語輔導計畫",
        "tutor_certificate_activity_text": "擔任華語輔導小老師，完成輔導服務",
    },
    {
        "code": "MARYLAND",
        "name_zh": "馬里蘭大學",
        "name_en": "University of Maryland",
        "is_active": True,
        "allow_tutee_initiate_invitation": True,
        "tutee_can_download_hours": True,
        "tutee_certificate_filename": "maryland_hours_certificate.pdf",
        "tutee_certificate_plan_name": "華語語言交換計畫",
        "tutee_certificate_activity_text": "完成語言交換",
        "tutor_certificate_filename": "",
        "tutor_certificate_plan_name": "",
        "tutor_certificate_activity_text": "",
    },
    {
        "code": "OTHER",
        "name_zh": "其他合作計畫",
        "name_en": "Other partner program",
        "is_active": True,
        "allow_tutee_initiate_invitation": False,
        "tutee_can_download_hours": True,
        "tutee_certificate_filename": "maryland_hours_certificate.pdf",
        "tutee_certificate_plan_name": "華語語言交換計畫",
        "tutee_certificate_activity_text": "完成語言交換",
        "tutor_certificate_filename": "",
        "tutor_certificate_plan_name": "",
        "tutor_certificate_activity_text": "",
    },
]


def seed_programs_and_backfill(apps, schema_editor):
    PartnerProgram = apps.get_model("accounts", "PartnerProgram")
    RosterEntry = apps.get_model("accounts", "RosterEntry")

    programs_by_code = {}
    for row in PROGRAM_SEED:
        program, _ = PartnerProgram.objects.get_or_create(code=row["code"], defaults=row)
        programs_by_code[row["code"]] = program

    for entry in RosterEntry.objects.exclude(program_source="NA"):
        program = programs_by_code.get(entry.program_source)
        if program:
            entry.program_id = program.pk
            entry.save(update_fields=["program"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_rosterentry_role_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='代碼 / Code')),
                ('name_zh', models.CharField(max_length=100, verbose_name='中文名稱 / Chinese name')),
                ('name_en', models.CharField(max_length=150, verbose_name='英文名稱 / English name')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中 / Active')),
                ('allow_tutee_initiate_invitation', models.BooleanField(default=False, verbose_name='Tutee 可主動邀請 Tutor / Tutee can initiate invitations')),
                ('tutee_can_download_hours', models.BooleanField(default=False, verbose_name='Tutee 可下載時數證明 / Tutee can download hour certificates')),
                ('tutee_certificate_filename', models.CharField(blank=True, help_text='檔名需已存在於 tutoring/resources/certificate_templates/。', max_length=150, verbose_name='Tutee 證明模板檔名 / Tutee certificate template filename')),
                ('tutee_certificate_plan_name', models.CharField(blank=True, max_length=100, verbose_name='Tutee 證明計畫名稱 / Tutee certificate plan name')),
                ('tutee_certificate_activity_text', models.CharField(blank=True, max_length=200, verbose_name='Tutee 證明活動描述 / Tutee certificate activity text')),
                ('tutor_certificate_filename', models.CharField(blank=True, help_text='檔名需已存在於 tutoring/resources/certificate_templates/。', max_length=150, verbose_name='Tutor 證明模板檔名 / Tutor certificate template filename')),
                ('tutor_certificate_plan_name', models.CharField(blank=True, max_length=100, verbose_name='Tutor 證明計畫名稱 / Tutor certificate plan name')),
                ('tutor_certificate_activity_text', models.CharField(blank=True, max_length=200, verbose_name='Tutor 證明活動描述 / Tutor certificate activity text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '合作計畫 / Partner program',
                'verbose_name_plural': '合作計畫 / Partner programs',
                'ordering': ['name_zh'],
            },
        ),
        migrations.AddField(
            model_name='rosterentry',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roster_entries', to='accounts.partnerprogram', verbose_name='所屬計畫 / Program'),
        ),
        migrations.RunPython(seed_programs_and_backfill, noop_reverse),
        migrations.RemoveField(
            model_name='rosterentry',
            name='program_source',
        ),
    ]
