# Generated by Django 5.2.16 on 2026-07-23 02:24

from django.db import migrations, models


SHARED_TEMPLATE = "csl_template.pdf"

CERTIFICATE_CONFIG = {
    "NTNU": {
        "tutee_certificate_filename": SHARED_TEMPLATE,
        "tutee_certificate_title_zh": "受輔導證明",
        "tutee_certificate_title_en": "Certificate of Tutoring Received",
        "tutor_certificate_filename": SHARED_TEMPLATE,
        "tutor_certificate_title_zh": "實習證明",
        "tutor_certificate_title_en": "Certificate of Counseling Practicum",
    },
    "MARYLAND": {
        "tutee_certificate_filename": SHARED_TEMPLATE,
        "tutee_certificate_title_zh": "語言交換證明",
        "tutee_certificate_title_en": "Certificate of Language Exchange",
        "tutor_certificate_filename": SHARED_TEMPLATE,
        "tutor_certificate_title_zh": "語言交換服務證明",
        "tutor_certificate_title_en": "Certificate of Language Exchange Service",
        "tutor_certificate_plan_name": "華語語言交換計畫",
        "tutor_certificate_activity_text": "提供語言交換服務",
    },
    "OTHER": {
        "tutee_certificate_filename": SHARED_TEMPLATE,
        "tutee_certificate_title_zh": "合作計畫證明",
        "tutee_certificate_title_en": "Certificate of Partner Program",
        "tutee_certificate_plan_name": "合作計畫",
        "tutee_certificate_activity_text": "完成合作計畫活動",
        "tutor_certificate_filename": SHARED_TEMPLATE,
        "tutor_certificate_title_zh": "合作計畫服務證明",
        "tutor_certificate_title_en": "Certificate of Partner Program Service",
        "tutor_certificate_plan_name": "合作計畫",
        "tutor_certificate_activity_text": "提供合作計畫服務",
    },
}


def apply_shared_template(apps, schema_editor):
    PartnerProgram = apps.get_model("accounts", "PartnerProgram")
    for code, fields in CERTIFICATE_CONFIG.items():
        PartnerProgram.objects.filter(code=code).update(**fields)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_partnerprogram_remove_rosterentry_program_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprogram',
            name='tutee_certificate_title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tutee 證明標題(英) / Tutee certificate title (English)'),
        ),
        migrations.AddField(
            model_name='partnerprogram',
            name='tutee_certificate_title_zh',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tutee 證明標題(中) / Tutee certificate title (Chinese)'),
        ),
        migrations.AddField(
            model_name='partnerprogram',
            name='tutor_certificate_title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tutor 證明標題(英) / Tutor certificate title (English)'),
        ),
        migrations.AddField(
            model_name='partnerprogram',
            name='tutor_certificate_title_zh',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tutor 證明標題(中) / Tutor certificate title (Chinese)'),
        ),
        migrations.AlterField(
            model_name='partnerprogram',
            name='tutee_certificate_filename',
            field=models.CharField(blank=True, help_text='檔名需已存在於 tutoring/resources/certificate_templates/。多個計畫可共用同一份底圖。', max_length=150, verbose_name='Tutee 證明模板檔名 / Tutee certificate template filename'),
        ),
        migrations.AlterField(
            model_name='partnerprogram',
            name='tutor_certificate_filename',
            field=models.CharField(blank=True, help_text='檔名需已存在於 tutoring/resources/certificate_templates/。多個計畫可共用同一份底圖。', max_length=150, verbose_name='Tutor 證明模板檔名 / Tutor certificate template filename'),
        ),
        migrations.RunPython(apply_shared_template, noop_reverse),
    ]
