# Generated by Django 5.2.16 on 2026-07-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_partnerprogram_tutee_certificate_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterentry',
            name='identity_category',
            field=models.CharField(blank=True, choices=[('LOCAL', '本地生 / Local student'), ('OVERSEAS', '僑生 / Overseas Chinese student'), ('INTERNATIONAL', '外籍生 / International student')], help_text='匯入時可留空，由使用者註冊時自行填寫。', max_length=16, verbose_name='學生類別 / Student category'),
        ),
        migrations.AlterField(
            model_name='rosterentry',
            name='name_zh',
            field=models.CharField(blank=True, help_text='匯入時可留空，由使用者註冊時自行填寫。', max_length=100, verbose_name='中文姓名 / Chinese name'),
        ),
    ]
