# Generated by Django 5.2.16 on 2026-08-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_deactivate_other_partner_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityquestionanswer',
            name='question_1',
            field=models.CharField(choices=[('Q1', '我第一所就讀的小學名稱？ / What was the name of my first elementary school?'), ('Q2', '我最喜歡的食物？ / What is my favorite food?'), ('Q3', '我最喜歡的一本書？ / What is my favorite book?'), ('Q4', "我第一位導師的姓氏？ / What was my first homeroom teacher's surname?"), ('Q5', '我最想造訪的城市？ / Which city would I most like to visit?'), ('Q6', '我自訂的一句秘密短語？ / What is my personal secret phrase?'), ('Q7', '我童年最喜歡的遊戲？ / What was my favorite childhood game?'), ('Q8', '我的第一隻寵物叫什麼名字？ / What was the name of my first pet?'), ('Q9', '我的綽號？ / What is my nickname?'), ('Q10', '我印象最深刻的旅行地點？ / What is my most memorable travel destination?'), ('Q11', '我最喜歡的一部電影？ / What is my favorite movie?'), ('Q12', '我最喜歡的一首歌？ / What is my favorite song?')], max_length=3),
        ),
        migrations.AlterField(
            model_name='securityquestionanswer',
            name='question_2',
            field=models.CharField(choices=[('Q1', '我第一所就讀的小學名稱？ / What was the name of my first elementary school?'), ('Q2', '我最喜歡的食物？ / What is my favorite food?'), ('Q3', '我最喜歡的一本書？ / What is my favorite book?'), ('Q4', "我第一位導師的姓氏？ / What was my first homeroom teacher's surname?"), ('Q5', '我最想造訪的城市？ / Which city would I most like to visit?'), ('Q6', '我自訂的一句秘密短語？ / What is my personal secret phrase?'), ('Q7', '我童年最喜歡的遊戲？ / What was my favorite childhood game?'), ('Q8', '我的第一隻寵物叫什麼名字？ / What was the name of my first pet?'), ('Q9', '我的綽號？ / What is my nickname?'), ('Q10', '我印象最深刻的旅行地點？ / What is my most memorable travel destination?'), ('Q11', '我最喜歡的一部電影？ / What is my favorite movie?'), ('Q12', '我最喜歡的一首歌？ / What is my favorite song?')], max_length=3),
        ),
        migrations.AlterField(
            model_name='securityquestionanswer',
            name='question_3',
            field=models.CharField(choices=[('Q1', '我第一所就讀的小學名稱？ / What was the name of my first elementary school?'), ('Q2', '我最喜歡的食物？ / What is my favorite food?'), ('Q3', '我最喜歡的一本書？ / What is my favorite book?'), ('Q4', "我第一位導師的姓氏？ / What was my first homeroom teacher's surname?"), ('Q5', '我最想造訪的城市？ / Which city would I most like to visit?'), ('Q6', '我自訂的一句秘密短語？ / What is my personal secret phrase?'), ('Q7', '我童年最喜歡的遊戲？ / What was my favorite childhood game?'), ('Q8', '我的第一隻寵物叫什麼名字？ / What was the name of my first pet?'), ('Q9', '我的綽號？ / What is my nickname?'), ('Q10', '我印象最深刻的旅行地點？ / What is my most memorable travel destination?'), ('Q11', '我最喜歡的一部電影？ / What is my favorite movie?'), ('Q12', '我最喜歡的一首歌？ / What is my favorite song?')], max_length=3),
        ),
    ]
