# Generated by Django 5.2.16 on 2026-08-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprogram',
            name='tutee_certificate_activity_text_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Tutee 證明活動描述(英) / Tutee certificate activity text (English)'),
        ),
        migrations.AddField(
            model_name='partnerprogram',
            name='tutee_certificate_plan_name_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tutee 證明計畫名稱(英) / Tutee certificate plan name (English)'),
        ),
        migrations.AddField(
            model_name='partnerprogram',
            name='tutor_certificate_activity_text_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Tutor 證明活動描述(英) / Tutor certificate activity text (English)'),
        ),
        migrations.AddField(
            model_name='partnerprogram',
            name='tutor_certificate_plan_name_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tutor 證明計畫名稱(英) / Tutor certificate plan name (English)'),
        ),
        migrations.AlterField(
            model_name='partnerprogram',
            name='tutee_certificate_activity_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tutee 證明活動描述(中) / Tutee certificate activity text (Chinese)'),
        ),
        migrations.AlterField(
            model_name='partnerprogram',
            name='tutee_certificate_plan_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tutee 證明計畫名稱(中) / Tutee certificate plan name (Chinese)'),
        ),
        migrations.AlterField(
            model_name='partnerprogram',
            name='tutor_certificate_activity_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tutor 證明活動描述(中) / Tutor certificate activity text (Chinese)'),
        ),
        migrations.AlterField(
            model_name='partnerprogram',
            name='tutor_certificate_plan_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tutor 證明計畫名稱(中) / Tutor certificate plan name (Chinese)'),
        ),
    ]
