# Generated by Django 5.2.16 on 2026-08-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_certificate_english_plan_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprogram',
            name='class_documents_enabled',
            field=models.BooleanField(default=False, help_text='開啟後，此計畫符合資格的 Tutor/Tutee 才會在選單看到「上課文件」並能查看已啟用的文件。 / When enabled, eligible Tutors/Tutees of this program see the "Class documents" menu item and can view active documents.', verbose_name='開放上課文件 / Class documents enabled'),
        ),
    ]
