# Generated by Django 5.2.16 on 2026-08-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_enable_maryland_class_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterentry',
            name='identity_category',
            field=models.CharField(blank=True, choices=[('LOCAL', '本地生 / Domestic student'), ('OVERSEAS', '僑生 / Overseas Chinese student'), ('INTERNATIONAL', '外籍生 / International student')], help_text='匯入時可留空，由使用者註冊時自行填寫。', max_length=16, verbose_name='學生類別 / Student category'),
        ),
    ]
