# Generated by Django 5.2.16 on 2026-08-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_create_cache_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='rosterentry',
            name='identity_category',
            field=models.CharField(blank=True, choices=[('LOCAL', '本地生 / Domestic student'), ('OVERSEAS', '僑生 / Overseas Chinese student'), ('HONG_KONG_MACAO', '港澳生 / Hong Kong and Macao student'), ('INTERNATIONAL', '外籍生 / International student')], help_text='匯入時可留空，由使用者註冊時自行填寫。', max_length=16, verbose_name='學生類別 / Student category'),
        ),
        migrations.AddConstraint(
            model_name='securityquestionanswer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('question_1', models.F('question_2')), _negated=True), models.Q(('question_1', models.F('question_3')), _negated=True), models.Q(('question_2', models.F('question_3')), _negated=True)), name='three_distinct_security_questions'),
        ),
    ]
