# Generated by Django 5.2.16 on 2026-08-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_user_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterentry',
            name='identity_category',
            field=models.CharField(blank=True, choices=[('LOCAL', '本地生 / Domestic student'), ('OVERSEAS', '僑生 / Overseas Chinese student'), ('HONG_KONG_MACAO', '港澳生 / Hong Kong and Macao student'), ('MAINLAND', '陸生 / Mainland Chinese student'), ('INTERNATIONAL', '外籍生 / International student')], help_text='匯入時可留空，由使用者註冊時自行填寫。', max_length=16, verbose_name='學生類別 / Student category'),
        ),
    ]
