# Generated by Django 5.2.17 on 2026-09-11 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_rosterentry_identity_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentOralExamPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=24, unique=True, verbose_name='學號 / Student ID')),
                ('imported_at', models.DateTimeField(auto_now=True, verbose_name='匯入時間 / Imported at')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_oral_exam_passes', to=settings.AUTH_USER_MODEL, verbose_name='匯入者 / Imported by')),
            ],
            options={
                'verbose_name': '系辦語音通過名單 / Department oral exam pass record',
                'verbose_name_plural': '系辦語音通過名單 / Department oral exam pass records',
                'ordering': ['student_id'],
            },
        ),
    ]
