# Generated by Django 5.2.17 on 2026-09-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_departmentoralexampass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentoralexampass',
            options={'ordering': ['student_id'], 'verbose_name': '系辦資格比對名單 / Department eligibility list record', 'verbose_name_plural': '系辦資格比對名單 / Department eligibility list records'},
        ),
        migrations.AddField(
            model_name='departmentoralexampass',
            name='list_type',
            field=models.CharField(choices=[('ORAL_EXAM_PASS', '語音通過 / Oral exam passed'), ('MARYLAND_COURSE_ROSTER', '馬里蘭修課名單 / Maryland course roster')], default='ORAL_EXAM_PASS', max_length=32, verbose_name='名單類型 / List type'),
        ),
    ]
