# Generated by Django 5.2.17 on 2026-09-24 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_departmentoralexampass_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='公告內容 / Announcement content')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='顯示順序 / Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='顯示中 / Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間 / Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間 / Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='建立者 / Created by')),
            ],
            options={
                'verbose_name': '公告欄項目 / Announcement',
                'verbose_name_plural': '公告欄項目 / Announcements',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
