# Generated by Django 5.2.17 on 2026-09-24 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='上次查看時間 / Last viewed at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_read_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
