# Generated by Django 5.2.17 on 2026-09-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_announcementreadstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content_en',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='英文公告內容 / English content'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='中文公告內容 / Chinese content'),
        ),
    ]
