# Generated by Django 5.2.17 on 2026-10-02 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_announcement_content_en_alter_announcement_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('QUALIFICATION', '口語能力證明 / Qualification'), ('HOURS', '輔導時數／課表 / Hours and schedule'), ('INCIDENT_REPORTS', '異常回報 / Incident reports')], max_length=20)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='上次查看時間 / Last viewed at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'section'), name='unique_dashboard_read_state_per_section')],
            },
        ),
    ]
