# Generated by Django 5.2.17 on 2026-10-06 06:44

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_dashboardreadstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OralExamAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(verbose_name='考試日期 / Exam date')),
                ('registration_deadline', models.DateTimeField(verbose_name='報名截止時間 / Registration deadline')),
                ('attachment_year_1', models.PositiveIntegerField(blank=True, null=True, verbose_name='附件年份 1 / Attachment year 1')),
                ('attachment_year_2', models.PositiveIntegerField(blank=True, null=True, verbose_name='附件年份 2 / Attachment year 2')),
                ('attachment_year_3', models.PositiveIntegerField(blank=True, null=True, verbose_name='附件年份 3 / Attachment year 3')),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to=accounts.models._oral_exam_attachment_upload_to, verbose_name='附件檔案(歷年試題合併檔) / Attachment file (combined exam papers)')),
                ('attachment_filename', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False, verbose_name='已發佈 / Published')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間 / Updated at')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最後更新者 / Last updated by')),
            ],
            options={
                'verbose_name': '線上口語考試公告 / Oral exam announcement',
                'verbose_name_plural': '線上口語考試公告 / Oral exam announcements',
            },
        ),
    ]
