# Generated by Django 5.2.17 on 2026-10-06 07:09

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_oralexamannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='OralExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(verbose_name='考試日期 / Exam date')),
                ('time_slot_1', models.TimeField(verbose_name='可口試時段 1 / Available time slot 1')),
                ('time_slot_2', models.TimeField(verbose_name='可口試時段 2 / Available time slot 2')),
                ('time_slot_3', models.TimeField(verbose_name='可口試時段 3 / Available time slot 3')),
                ('payment_proof', models.FileField(upload_to=accounts.models._oral_exam_payment_proof_upload_to, verbose_name='繳費紀錄 / Payment proof')),
                ('payment_proof_filename', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='報名時間 / Submitted at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間 / Updated at')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oral_exam_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '線上口語考試報名 / Oral exam registration',
                'verbose_name_plural': '線上口語考試報名 / Oral exam registrations',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('tutor', 'exam_date'), name='one_oral_exam_registration_per_tutor_per_exam')],
            },
        ),
    ]
