# Generated by Django 5.2.17 on 2026-10-06 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_oralexamregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='oralexamregistration',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登記時間 / Confirmed at'),
        ),
        migrations.AddField(
            model_name='oralexamregistration',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='登記者 / Confirmed by'),
        ),
    ]
