# Generated by Django 5.2.17 on 2026-10-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_oralexamregistration_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oralexamregistration',
            name='exam_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='考試順序 / Exam order'),
        ),
        migrations.AddField(
            model_name='oralexamregistration',
            name='exam_time',
            field=models.TimeField(blank=True, null=True, verbose_name='考試時間 / Exam time'),
        ),
    ]
