# Generated by Django 5.2.17 on 2026-10-06 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_oralexamregistration_exam_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oralexamregistration',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='oralexamregistration',
            name='confirmed_by',
        ),
        migrations.AddField(
            model_name='oralexamregistration',
            name='review_note',
            field=models.TextField(blank=True, verbose_name='留言 / Note'),
        ),
        migrations.AddField(
            model_name='oralexamregistration',
            name='review_status',
            field=models.CharField(choices=[('PENDING', '尚未核對 / Pending'), ('CONFIRMED', '已登記 / Confirmed'), ('NEEDS_REVISION', '補件 / Needs additional documents')], default='PENDING', max_length=20, verbose_name='核對狀態 / Review status'),
        ),
        migrations.AddField(
            model_name='oralexamregistration',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='核對時間 / Reviewed at'),
        ),
        migrations.AddField(
            model_name='oralexamregistration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='核對者 / Reviewed by'),
        ),
    ]
