# Generated by Django 5.2.17 on 2026-10-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_oralexamregistration_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oralexamregistration',
            name='meet_link',
            field=models.URLField(blank=True, verbose_name='Google Meet 連結 / Google Meet link'),
        ),
    ]
