# Generated by Django 5.2.16 on 2026-07-17 17:04

import django.db.models.deletion
import tutoring.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=80, verbose_name='學期名稱 / Semester name')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文名稱 / English name')),
                ('starts_on', models.DateField(verbose_name='開始日期 / Start date')),
                ('ends_on', models.DateField(verbose_name='結束日期 / End date')),
                ('invitation_deadline', models.DateField(verbose_name='配對截止日 / Matching deadline')),
                ('is_active', models.BooleanField(default=False, verbose_name='目前學期 / Current semester')),
            ],
            options={
                'verbose_name': '學期 / Semester',
                'verbose_name_plural': '學期 / Semesters',
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='QualificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='qualifications/%Y/%m/', validators=[tutoring.models.validate_qualification_file], verbose_name='資格證明 / Qualification document')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NOT_SUBMITTED', '未提交 / Not submitted'), ('PENDING', '待審核 / Pending review'), ('APPROVED', '已通過 / Approved'), ('REJECTED', '需補件 / Revision required')], default='PENDING', max_length=16)),
                ('review_note', models.TextField(blank=True, verbose_name='審核備註 / Review note')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_qualifications', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '資格證明 / Qualification document',
                'verbose_name_plural': '資格證明 / Qualification documents',
                'ordering': ['-updated_at'],
            },
        ),
    ]
