# Generated by Django 5.2.16 on 2026-07-17 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TuteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', '男 / Male'), ('FEMALE', '女 / Female'), ('NON_BINARY', '非二元 / Non-binary'), ('UNDISCLOSED', '不願透露 / Prefer not to say')], max_length=16, verbose_name='性別 / Gender')),
                ('native_language', models.CharField(max_length=80, verbose_name='母語 / Native language')),
                ('nationality', models.CharField(max_length=80, verbose_name='國籍 / Nationality')),
                ('department', models.CharField(max_length=150, verbose_name='系所 / Department')),
                ('overall_level', models.CharField(max_length=50, verbose_name='整體華語程度 / Overall Chinese level')),
                ('learning_duration', models.CharField(blank=True, max_length=80, verbose_name='華語學習時間 / Learning duration')),
                ('level_listening', models.PositiveSmallIntegerField(default=3, verbose_name='聽力 / Listening')),
                ('level_speaking', models.PositiveSmallIntegerField(default=3, verbose_name='口說 / Speaking')),
                ('level_reading', models.PositiveSmallIntegerField(default=3, verbose_name='閱讀 / Reading')),
                ('level_writing', models.PositiveSmallIntegerField(default=3, verbose_name='寫作 / Writing')),
                ('target_skills', models.JSONField(default=list, verbose_name='希望加強項目 / Target skills')),
                ('skills_to_improve', models.TextField(blank=True, verbose_name='學習需求 / Learning needs')),
                ('preferred_days', models.JSONField(default=list, verbose_name='偏好星期 / Preferred days')),
                ('preferred_time_slots', models.JSONField(default=list, verbose_name='偏好時段 / Preferred time slots')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutee 個人檔案 / Tutee profile',
                'verbose_name_plural': 'Tutee 個人檔案 / Tutee profiles',
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', '男 / Male'), ('FEMALE', '女 / Female'), ('NON_BINARY', '非二元 / Non-binary'), ('UNDISCLOSED', '不願透露 / Prefer not to say')], max_length=16, verbose_name='性別 / Gender')),
                ('native_language', models.CharField(max_length=80, verbose_name='母語 / Native language')),
                ('nationality', models.CharField(max_length=80, verbose_name='國籍 / Nationality')),
                ('department', models.CharField(default='華語文教學系', max_length=150, verbose_name='系所 / Department')),
                ('level_listening', models.PositiveSmallIntegerField(default=0, verbose_name='聽力教學 / Listening')),
                ('level_speaking', models.PositiveSmallIntegerField(default=0, verbose_name='口說教學 / Speaking')),
                ('level_reading', models.PositiveSmallIntegerField(default=0, verbose_name='閱讀教學 / Reading')),
                ('level_writing', models.PositiveSmallIntegerField(default=0, verbose_name='寫作教學 / Writing')),
                ('teaching_notes', models.TextField(blank=True, verbose_name='教學簡介 / Teaching notes')),
                ('available_days', models.JSONField(default=list, verbose_name='可配合星期 / Available days')),
                ('available_time_slots', models.JSONField(default=list, verbose_name='可配合時段 / Available time slots')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutor 個人檔案 / Tutor profile',
                'verbose_name_plural': 'Tutor 個人檔案 / Tutor profiles',
            },
        ),
    ]
