# Generated by Django 5.2.16 on 2026-07-18 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_tuteeprofile_tutorprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '等待回覆 / Pending'), ('ACCEPTED', '已接受 / Accepted'), ('REJECTED', '已拒絕 / Declined'), ('CANCELLED', '已取消 / Cancelled'), ('EXPIRED', '已過期 / Expired')], default='PENDING', max_length=12)),
                ('expires_at', models.DateTimeField(verbose_name='邀請到期時間 / Invitation expiry')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='回覆時間 / Responded at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_matching_invitations', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matching_invitations', to='tutoring.semester')),
                ('tutee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutee_invitations', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutor_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '配對邀請 / Matching invitation',
                'verbose_name_plural': '配對邀請 / Matching invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', '輔導中 / Active'), ('ENDED', '已結束 / Ended')], default='ACTIVE', max_length=8)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=80, verbose_name='結束原因 / End reason')),
                ('invitation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pairing', to='tutoring.matchinginvitation')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pairings', to='tutoring.semester')),
                ('tutee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutee_pairings', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutor_pairings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '輔導配對 / Pairing',
                'verbose_name_plural': '輔導配對 / Pairings',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='matchinginvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('semester', 'tutor', 'tutee'), name='unique_pending_invitation_per_pair'),
        ),
        migrations.AddConstraint(
            model_name='pairing',
            constraint=models.UniqueConstraint(fields=('semester', 'tutor', 'tutee'), name='unique_pair_per_semester'),
        ),
        migrations.AddConstraint(
            model_name='pairing',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('semester', 'tutee'), name='one_active_tutor_per_tutee_semester'),
        ),
    ]
