# Generated by Django 5.2.16 on 2026-07-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_matchinginvitation_pairing_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_semester'),
        ),
    ]
