# Generated by Django 5.2.16 on 2026-07-19 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0004_semester_only_one_active_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField(verbose_name='上課日期 / Class date')),
                ('start_time', models.TimeField(verbose_name='開始時間 / Start time')),
                ('duration', models.DecimalField(choices=[(0.5, '0.5 小時 / hour'), (1, '1 小時 / hour'), (1.5, '1.5 小時 / hours'), (2, '2 小時 / hours')], decimal_places=1, max_digits=2, verbose_name='時數 / Duration')),
                ('recurrence_group', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', '已排課 / Scheduled'), ('CANCELLED', '已取消 / Cancelled')], default='SCHEDULED', max_length=12)),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='取消原因 / Cancellation reason')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_class_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_class_sessions', to=settings.AUTH_USER_MODEL)),
                ('pairing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_sessions', to='tutoring.pairing')),
            ],
            options={
                'verbose_name': '課程 / Class session',
                'verbose_name_plural': '課程 / Class sessions',
                'ordering': ['class_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150, verbose_name='上課地點 / Location')),
                ('topic', models.CharField(max_length=200, verbose_name='課堂主題 / Topic')),
                ('content', models.TextField(verbose_name='課堂內容 / Class content')),
                ('reflection', models.TextField(verbose_name='學習成果與回饋 / Outcome and reflection')),
                ('remarks', models.TextField(blank=True, verbose_name='備註 / Remarks')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_makeup', models.BooleanField(default=False, verbose_name='補課堂紀錄 / Makeup class record')),
                ('makeup_reason', models.TextField(blank=True, verbose_name='補登原因 / Makeup reason')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_records', to='tutoring.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='ClassConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_confirmed', models.BooleanField(default=False)),
                ('record_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('CONFIRMED', '確認無誤 / Confirmed'), ('REVISION', '請對方修改 / Revision requested'), ('ISSUE', '回報問題 / Report issue')], max_length=12)),
                ('note', models.TextField(blank=True, verbose_name='說明 / Note')),
                ('confirmed_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_confirmations', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_class_confirmations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='tutoring.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField()),
                ('is_makeup', models.BooleanField(default=False, verbose_name='補簽到 / Makeup check-in')),
                ('makeup_reason', models.TextField(blank=True, verbose_name='補登原因 / Makeup reason')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_attendances', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='tutoring.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='MakeupReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', '等待雙方確認 / Waiting for mutual confirmation'), ('PENDING', '待管理員審核 / Pending admin review'), ('APPROVED', '已核准 / Approved'), ('REJECTED', '未核准 / Rejected')], default='WAITING', max_length=12)),
                ('review_note', models.TextField(blank=True, verbose_name='審核備註 / Review note')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_makeup_requests', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_review', to='tutoring.classsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.CheckConstraint(condition=models.Q(('duration__in', [0.5, 1, 1.5, 2])), name='valid_class_session_duration'),
        ),
        migrations.AddConstraint(
            model_name='classrecord',
            constraint=models.UniqueConstraint(fields=('session', 'author'), name='one_record_per_person'),
        ),
        migrations.AddConstraint(
            model_name='classconfirmation',
            constraint=models.UniqueConstraint(fields=('session', 'reviewer'), name='one_confirmation_per_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('session', 'participant'), name='one_attendance_per_person'),
        ),
    ]
