# Generated by Django 5.2.16 on 2026-07-19 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_classsession_classrecord_classconfirmation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('CANNOT_REACH', '聯絡不到對方 / Cannot reach the other participant'), ('ABSENT', '對方未出席 / The other participant is absent'), ('SCHEDULE_ISSUE', '上課時間或地點有問題 / Schedule or location issue'), ('OTHER', '其他緊急狀況 / Other urgent issue')], max_length=20, verbose_name='通報原因 / Alert reason')),
                ('note', models.TextField(blank=True, verbose_name='通報說明 / Alert note')),
                ('status', models.CharField(choices=[('ACTIVE', '待處理 / Active'), ('CANCELLED', '已取消 / Cancelled')], default='ACTIVE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_class_alerts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_alerts', to='tutoring.classsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_class_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '課堂通報 / Class alert',
                'verbose_name_plural': '課堂通報 / Class alerts',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('session', 'reporter'), name='one_active_class_alert_per_reporter')],
            },
        ),
    ]
