# Generated by Django 5.2.16 on 2026-07-19 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0006_classalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PairingReleaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('NO_SHOW', '老師或學生未出席 / Teacher or student repeatedly absent'), ('UNREACHABLE', '老師或學生失去聯絡 / Teacher or student unreachable'), ('SCHEDULE_CONFLICT', '雙方時間無法配合 / Schedule conflict'), ('CONDUCT', '態度或行為問題 / Conduct or behavior concern'), ('OTHER', '其他原因 / Other')], max_length=24, verbose_name='解除原因 / Release reason')),
                ('reason_note', models.TextField(blank=True, verbose_name='申請說明 / Request note')),
                ('status', models.CharField(choices=[('PENDING', '等待管理員處理 / Pending admin review'), ('APPROVED', '管理員已核准 / Approved by admin'), ('AUTO_APPROVED', '系統自動解除 / Automatically released'), ('REJECTED', '管理員未核准 / Rejected by admin')], default='PENDING', max_length=16, verbose_name='處理狀態 / Review status')),
                ('auto_resolve_at', models.DateTimeField(blank=True, null=True, verbose_name='自動解除時間 / Automatic release time')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, verbose_name='審核備註 / Review note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pairing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_requests', to='tutoring.pairing')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pairing_release_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pairing_release_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '解除配對申請 / Pairing release request',
                'verbose_name_plural': '解除配對申請 / Pairing release requests',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('pairing',), name='one_pending_release_request_per_pairing')],
            },
        ),
    ]
