# Generated by Django 5.2.16 on 2026-07-19 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0007_pairingreleaserequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PairingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000, verbose_name='訊息 / Message')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='閱讀時間 / Read at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '配對私訊 / Pairing message',
                'verbose_name_plural': '配對私訊 / Pairing messages',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='semester',
            name='only_one_active_semester',
        ),
        migrations.AddField(
            model_name='semester',
            name='invitation_starts_on',
            field=models.DateField(blank=True, null=True, verbose_name='配對開始日 / Matching start date'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='啟用 / Enabled'),
        ),
        migrations.AddField(
            model_name='pairingmessage',
            name='pairing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='tutoring.pairing'),
        ),
        migrations.AddField(
            model_name='pairingmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_pairing_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pairingmessage',
            index=models.Index(fields=['pairing', 'created_at'], name='tutoring_pa_pairing_944742_idx'),
        ),
    ]
