# Generated by Django 5.2.16 on 2026-07-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0008_pairingmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='invitation_deadline',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='invitation_starts_on',
        ),
    ]
