# Generated by Django 5.2.16 on 2026-07-22 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0009_remove_semester_invitation_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('STUDENT_ABSENT', '學生缺席 / Student absent'), ('TUTOR_ABSENT', '老師缺席 / Tutor absent'), ('VENUE_ISSUE', '場地問題 / Venue issue'), ('LEARNING_PROGRESS', '學習進度問題 / Learning progress issue'), ('SAFETY', '人身安全 / Safety concern'), ('OTHER', '其他 / Other')], max_length=20, verbose_name='分類 / Category')),
                ('content', models.TextField(verbose_name='回報內容 / Report content')),
                ('status', models.CharField(choices=[('PENDING', '待處理 / Pending'), ('RESOLVED', '已處理 / Resolved')], default='PENDING', max_length=12)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, verbose_name='處理備註 / Resolution note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incident_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_incident_reports', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='tutoring.classsession')),
            ],
            options={
                'verbose_name': '異常回報 / Incident report',
                'verbose_name_plural': '異常回報 / Incident reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
