# Generated by Django 5.2.16 on 2026-07-22 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0010_incidentreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classalert',
            name='resolution_note',
            field=models.TextField(blank=True, verbose_name='處理備註 / Resolution note'),
        ),
        migrations.AddField(
            model_name='classalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_class_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classalert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '待處理 / Active'), ('CANCELLED', '已取消 / Cancelled'), ('RESOLVED', '已處理 / Resolved')], default='ACTIVE', max_length=12),
        ),
    ]
