# Generated by Django 5.2.16 on 2026-07-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0011_classalert_resolution_note_classalert_resolved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classalert',
            name='resolution_note',
            field=models.TextField(blank=True, verbose_name='紀錄備註 / Log note'),
        ),
        migrations.AlterField(
            model_name='classalert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '待處理 / Active'), ('CANCELLED', '已取消 / Cancelled'), ('RESOLVED', '已紀錄 / Logged')], default='ACTIVE', max_length=12),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='resolution_note',
            field=models.TextField(blank=True, verbose_name='紀錄備註 / Log note'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('PENDING', '待處理 / Pending'), ('RESOLVED', '已紀錄 / Logged')], default='PENDING', max_length=12),
        ),
    ]
