# Generated by Django 5.2.16 on 2026-07-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0012_alter_classalert_resolution_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecord',
            name='skills_practiced',
            field=models.JSONField(blank=True, default=list, verbose_name='授課類型 / Skills practiced'),
        ),
    ]
