# Generated by Django 5.2.16 on 2026-07-25 11:36

import tutoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0013_classrecord_skills_practiced'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecord',
            name='attachment',
            field=models.FileField(blank=True, upload_to='class_record_attachments/%Y/%m/', validators=[tutoring.models.validate_class_record_attachment], verbose_name='附件 / Attachment'),
        ),
    ]
