# Generated by Django 5.2.16 on 2026-07-25 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_deactivate_other_partner_program'),
        ('tutoring', '0014_classrecord_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HourAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='調整時數 / Adjustment hours')),
                ('reason', models.TextField(verbose_name='調整原因 / Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_hour_adjustments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hour_adjustments', to='accounts.partnerprogram')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hour_adjustments', to='tutoring.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hour_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '時數調整紀錄 / Hour adjustment',
                'verbose_name_plural': '時數調整紀錄 / Hour adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
