# Generated by Django 5.2.16 on 2026-08-04 15:33

import tutoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0015_houradjustment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualificationdocument',
            options={'ordering': ['-updated_at'], 'verbose_name': '口語能力證明 / Oral proficiency document', 'verbose_name_plural': '口語能力證明 / Oral proficiency documents'},
        ),
        migrations.AlterField(
            model_name='qualificationdocument',
            name='file',
            field=models.FileField(upload_to='qualifications/%Y/%m/', validators=[tutoring.models.validate_qualification_file], verbose_name='口語能力證明 / Oral proficiency document'),
        ),
    ]
