# Generated by Django 5.2.16 on 2026-08-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0016_alter_qualificationdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecord',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='課堂內容 / Class content'),
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='remarks',
            field=models.TextField(blank=True, max_length=2000, verbose_name='備註 / Remarks'),
        ),
    ]
