# Generated by Django 5.2.16 on 2026-08-04 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_nickname'),
        ('tutoring', '0017_alter_classrecord_content_alter_classrecord_remarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='applicable_users',
            field=models.ManyToManyField(blank=True, related_name='applicable_semesters', to=settings.AUTH_USER_MODEL, verbose_name='適用對象 / Applicable users'),
        ),
        migrations.AddField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='accounts.partnerprogram', verbose_name='合作計畫 / Partner program'),
        ),
    ]
