# Generated by Django 5.2.16 on 2026-08-05 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0018_semester_applicable_users_semester_program'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_created_pairings', to=settings.AUTH_USER_MODEL, verbose_name='Admin 建立者 / Created by (admin)'),
        ),
    ]
