# Generated by Django 5.2.16 on 2026-08-05 19:11

import django.db.models.deletion
import tutoring.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_partnerprogram_class_documents_enabled'),
        ('tutoring', '0019_pairing_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_zh', models.CharField(max_length=200, verbose_name='中文標題 / Chinese title')),
                ('title_en', models.CharField(max_length=200, verbose_name='英文標題 / English title')),
                ('file', models.FileField(upload_to='class_documents/%Y/%m/', validators=[tutoring.models.validate_class_document_file], verbose_name='檔案 / File')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用 / Active')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間 / Uploaded at')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_documents', to='accounts.partnerprogram')),
                ('semester', models.ForeignKey(blank=True, help_text='留空表示適用此計畫所有學期。 / Leave blank to apply to every semester of this program.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_documents', to='tutoring.semester', verbose_name='適用學期 / Applicable semester')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '上課文件 / Class document',
                'verbose_name_plural': '上課文件 / Class documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
