# Generated by Django 5.2.16 on 2026-08-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0020_classdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecord',
            name='evidence_links',
            field=models.JSONField(blank=True, default=list, help_text='僅 Tutor 課堂紀錄使用,取代附件上傳(item 14)。 / Tutor-only, replaces the file attachment.', verbose_name='佐證連結 / Evidence links'),
        ),
    ]
