# Generated by Django 5.2.16 on 2026-08-08 17:01

import tutoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0021_classrecord_evidence_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='original_attachment_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='classdocument',
            name='file',
            field=models.FileField(upload_to=tutoring.models.class_document_upload_to, validators=[tutoring.models.validate_class_document_file], verbose_name='檔案 / File'),
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='attachment',
            field=models.FileField(blank=True, upload_to=tutoring.models.class_record_attachment_upload_to, validators=[tutoring.models.validate_class_record_attachment], verbose_name='附件 / Attachment'),
        ),
        migrations.AlterField(
            model_name='qualificationdocument',
            name='file',
            field=models.FileField(upload_to=tutoring.models.qualification_upload_to, validators=[tutoring.models.validate_qualification_file], verbose_name='口語能力證明 / Oral proficiency document'),
        ),
    ]
