# Generated by Django 5.2.16 on 2026-08-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0022_classdocument_original_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecord',
            name='content',
            field=models.TextField(max_length=500, verbose_name='課堂內容 / Class content'),
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='evidence_links',
            field=models.JSONField(blank=True, default=list, help_text='雙方課堂紀錄皆使用佐證連結。 / Evidence links are required for both participants.', verbose_name='佐證連結 / Evidence links'),
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, verbose_name='備註 / Remarks'),
        ),
    ]
