# Generated by Django 5.2.17 on 2026-08-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0023_alter_classrecord_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationdocument',
            name='status',
            field=models.CharField(choices=[('NOT_SUBMITTED', '未提交 / Not submitted'), ('PENDING', '待審核 / Pending review'), ('APPROVED', '已通過 / Approved'), ('REJECTED', '已拒絕 / Rejected')], default='PENDING', max_length=16),
        ),
    ]
