# Generated by Django 5.2.17 on 2026-08-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0024_alter_qualificationdocument_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='applicable_users',
        ),
    ]
