# Generated by Django 5.2.17 on 2026-08-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0025_remove_semester_applicable_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeupreview',
            name='status',
            field=models.CharField(choices=[('WAITING', '等待雙方確認 / Waiting for mutual confirmation'), ('PENDING', '等待管理員核准 / Waiting for admin approval'), ('APPROVED', '已核准 / Approved'), ('REJECTED', '未核准 / Rejected')], default='WAITING', max_length=12),
        ),
    ]
