# Generated by Django 5.2.17 on 2026-09-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0026_alter_makeupreview_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrecord',
            name='skills_practiced',
        ),
        migrations.AddField(
            model_name='classrecord',
            name='individual_progress',
            field=models.TextField(default='（此欄位為新增，舊紀錄無資料）/ (Added after this record was created; no data available)', max_length=500, verbose_name='個別學習情形 / Individual learning progress'),
        ),
        migrations.AddField(
            model_name='classrecord',
            name='materials_used',
            field=models.TextField(default='（此欄位為新增，舊紀錄無資料）/ (Added after this record was created; no data available)', max_length=200, verbose_name='使用之教材、教具及設備 / Materials, teaching aids, and equipment used'),
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='content',
            field=models.TextField(max_length=500, verbose_name="本日教學範圍與流程 / Today's teaching scope and process"),
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, verbose_name='心得回饋或針對個別學習情況之改善方法 / Reflections and feedback, or improvement methods for individual learning'),
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='本次教學目標 / Teaching goal for this session'),
        ),
    ]
