# Generated by Django 5.2.17 on 2026-09-02 18:28

from django.db import migrations, models

_LEGACY_PLACEHOLDER = "（此欄位為新增，舊紀錄無資料）/ (Added after this record was created; no data available)"


def clear_legacy_placeholder(apps, schema_editor):
    """0027 backfilled these two new required fields with a literal placeholder
    string so existing rows would pass the NOT NULL migration. Product decided
    the placeholder shouldn't live in the stored data itself — templates now
    show a friendly "predates this field" message when the value is empty, so
    revert those rows back to "" instead."""
    ClassRecord = apps.get_model("tutoring", "ClassRecord")
    ClassRecord.objects.filter(materials_used=_LEGACY_PLACEHOLDER).update(materials_used="")
    ClassRecord.objects.filter(individual_progress=_LEGACY_PLACEHOLDER).update(individual_progress="")


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0027_remove_classrecord_skills_practiced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecord',
            name='individual_progress',
            field=models.TextField(default='', max_length=500, verbose_name='個別學習情形 / Individual learning progress'),
        ),
        migrations.AlterField(
            model_name='classrecord',
            name='materials_used',
            field=models.TextField(default='', max_length=200, verbose_name='使用之教材、教具及設備 / Materials, teaching aids, and equipment used'),
        ),
        migrations.RunPython(clear_legacy_placeholder, migrations.RunPython.noop),
    ]
