# Generated by Django 5.2.17 on 2026-09-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0028_alter_classrecord_individual_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='teaching_notes',
            field=models.TextField(blank=True, max_length=500, verbose_name='教學簡介 / Teaching notes'),
        ),
    ]
