# Generated by Django 5.2.17 on 2026-09-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0031_grandfather_valid_classes_into_class_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationdocument',
            name='tutor_note',
            field=models.TextField(blank=True, verbose_name='上傳說明 / Note to reviewer'),
        ),
    ]
