# Generated by Django 5.2.17 on 2026-09-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0032_qualificationdocument_tutor_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classreview',
            name='status',
            field=models.CharField(choices=[('WAITING', '等待雙方確認 / Waiting for mutual confirmation'), ('PENDING', '等待管理員核准 / Waiting for admin approval'), ('APPROVED', '已通過 / Approved'), ('REJECTED', '未通過 / Rejected')], default='WAITING', max_length=12),
        ),
        migrations.AlterField(
            model_name='pairingreleaserequest',
            name='status',
            field=models.CharField(choices=[('PENDING', '等待管理員處理 / Pending admin review'), ('APPROVED', '管理員已通過 / Approved by admin'), ('AUTO_APPROVED', '系統自動解除 / Automatically released'), ('REJECTED', '管理員未通過 / Rejected by admin')], default='PENDING', max_length=16, verbose_name='處理狀態 / Review status'),
        ),
        migrations.AlterField(
            model_name='qualificationdocument',
            name='status',
            field=models.CharField(choices=[('NOT_SUBMITTED', '未提交 / Not submitted'), ('PENDING', '待審核 / Pending review'), ('APPROVED', '已通過 / Approved'), ('REJECTED', '未通過 / Rejected')], default='PENDING', max_length=16),
        ),
    ]
