# Generated by Django 5.2.17 on 2026-09-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0033_alter_classreview_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairingreleaserequest',
            name='counterpart_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='對方已讀時間 / Counterpart acknowledged at'),
        ),
    ]
