# Generated by Django 5.2.17 on 2026-09-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0034_pairingreleaserequest_counterpart_acknowledged_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='tutoring.classsession'),
        ),
    ]
