# Generated by Django 5.2.17 on 2026-09-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0035_alter_incidentreport_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='session',
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='category',
            field=models.CharField(choices=[('STUDENT_ABSENT', '學生缺席 / Student absent'), ('TUTOR_ABSENT', '老師缺席 / Tutor absent'), ('VENUE_ISSUE', '場地問題 / Venue issue'), ('LEARNING_PROGRESS', '學習進度問題 / Learning progress issue'), ('SAFETY', '人身安全 / Safety concern'), ('SYSTEM_ISSUE', '系統問題 / System issue'), ('OTHER', '其他 / Other')], max_length=20, verbose_name='分類 / Category'),
        ),
    ]
