# Generated by Django 5.2.17 on 2026-09-23 16:12

import tutoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0037_matchingexclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='attachment',
            field=models.FileField(blank=True, upload_to=tutoring.models.incident_report_attachment_upload_to, validators=[tutoring.models.validate_qualification_file], verbose_name='附件（選填） / Attachment (optional)'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='original_attachment_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
