# Generated by Django 5.2.17 on 2026-09-30 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0038_incidentreport_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReportReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='回覆內容 / Reply content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送出時間 / Sent at')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tutoring.incidentreport')),
            ],
            options={
                'verbose_name': '異常回報追加回覆 / Incident report reply',
                'verbose_name_plural': '異常回報追加回覆 / Incident report replies',
                'ordering': ['created_at'],
            },
        ),
    ]
