# Generated by Django 5.2.17 on 2026-10-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0039_incidentreportreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecord',
            name='content',
            field=models.TextField(max_length=500, verbose_name="本日教學範圍與完整流程 / Today's teaching scope and complete process"),
        ),
    ]
