# Generated by Django 5.2.17 on 2026-10-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0040_alter_classrecord_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classreview',
            name='review_note',
            field=models.TextField(blank=True, verbose_name='審核意見 / Review comments'),
        ),
        migrations.AlterField(
            model_name='classreview',
            name='status',
            field=models.CharField(choices=[('WAITING', '等待雙方確認 / Waiting for mutual confirmation'), ('PENDING', '等待管理員核准 / Waiting for admin approval'), ('APPROVED', '通過 / Approved'), ('REJECTED', '未通過 / Rejected'), ('REVISE', '待補正 / Revise')], default='WAITING', max_length=12),
        ),
    ]
