# Generated by Django 5.2.17 on 2026-10-05 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0043_backfill_classreviewdecision_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRecordRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=500)),
                ('materials_used', models.TextField(blank=True, default='', max_length=200)),
                ('individual_progress', models.TextField(blank=True, default='', max_length=500)),
                ('remarks', models.TextField(blank=True, max_length=500)),
                ('evidence_links', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_record_revisions', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='tutoring.classrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
